version: '3.7'

x-base: &base
  build:
    context: ./
    dockerfile: ./Dockerfile

services:
  tcp_server:
    <<: *base
    container_name: tcp_server
    command: /usr/local/bin/tcp_server
    ports:
      - '8000:8000'
    environment:
      RUST_LOG: debug
    restart: always


  tcp_client:
    <<: *base
    container_name: tcp_client
    command: /usr/local/bin/tcp_client
    depends_on:
      - tcp_server
