* Tcp word of wisdom server with dos protection using POW algo
** Project structure
#+begin_src

  tcp_server
    src
      config.rs
      errors.rs
      main.rs
      lib.rs
    Cargo.toml
    config.yaml

  tcp_client
    src
      main.rs
    Cargo.toml

Dockerfile
docker-compose.yaml
Readme.org
#+end_src


** Build
*** To run localy
#+begin_src
Change
let mut stream = TcpStream::connect("tcp_server:8000")?;

in ./tcp_client/src/main.rs to

let mut stream = TcpStream::connect("0.0.0.0:8000")?;
#+end_src

#+begin_src
cd tcp_server

cargo run
#+end_src


And to run client use this command in another therminal
#+begin_src
cd tcp_client

cargo run
#+end_src

*** To run from docker
Run from terminal
#+begin_src
docker compose up -d
#+end_src

To check logs of tcp_client

#+begin_src
docker logs tcp_client
#+end_src

** Problem Statement
*** Design and implement a TCP server called "Word of Wisdom" server.

**** Requirements
- TCP server should be protected from DDOS attacks with the Prof of Work (https://en.wikipedia.org/wiki/Proof_of_work),
  the challenge-response protocol should be used.
- The choice of the POW algorithm should be explained.
- After Prof Of Work verification, server should send one of the quotes from “word of wisdom” book or any other collection of the quotes.
- Docker file should be provided both for the server and for the client that solves the POW challenge
